name: Send Message
on:
  schedule:
    # 21 UTC is 00 UTC+3
    - cron: '0 21 * * *'

jobs:
  run:
    name: Run script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.2.5

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prod

      - name: Run script
        run: pnpm start
        env:
          WH_ID: ${{ secrets.WH_ID }}
          WH_TOKEN: ${{ secrets.WH_TOKEN }}
